// Данные прайс-листа
const priceData = [
  {
    group: "Tulipa",
    sort: "tr",
    name: "Aafke",
    size: "12/+",
    color: "pink",
    priceRub100: "32.2",
    priceEuro: "0.32",
    priceRub95: "30.6",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Accent",
    size: "12/+",
    color: "yellow/red",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Ace of spades",
    size: "12/+",
    color: "red",
    priceRub100: "31.6",
    priceEuro: "0.32",
    priceRub95: "30.0",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Ace Pink",
    size: "12/+",
    color: "pink",
    priceRub100: "31.6",
    priceEuro: "0.32",
    priceRub95: "30.0",
  },
  {
    group: "Tulipa",
    sort: "dh",
    name: "Ad Rem",
    size: "12/+",
    color: "red/yellow",
    priceRub100: "29.9",
    priceEuro: "0.30",
    priceRub95: "28.4",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Adore",
    size: "12/+",
    color: "dark pink",
    priceRub100: "38.0",
    priceEuro: "0.38",
    priceRub95: "36.1",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Affaire",
    size: "12/+",
    color: "white/purple",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Albatros",
    size: "12/+",
    color: "white",
    priceRub100: "41.1",
    priceEuro: "0.41",
    priceRub95: "39.1",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Algarve",
    size: "12/+",
    color: "pink",
    priceRub100: "28.1",
    priceEuro: "0.28",
    priceRub95: "26.7",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Alibi",
    size: "12/+",
    color: "pink",
    priceRub100: "30.7",
    priceEuro: "0.31",
    priceRub95: "29.2",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Alibi Dark Rose ( pink breeze )",
    size: "12/+",
    color: "pink",
    priceRub100: "31.6",
    priceEuro: "0.32",
    priceRub95: "30.0",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Alibi Soft Rose (Sweet Breeze)",
    size: "12/+",
    color: "rose",
    priceRub100: "35.1",
    priceEuro: "0.35",
    priceRub95: "33.3",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Alison Bradley",
    size: "12/+",
    color: "purple",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Aloha",
    size: "12/+",
    color: "red/yellow",
    priceRub100: "31.0",
    priceEuro: "0.31",
    priceRub95: "29.5",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Amedea",
    size: "12/+",
    color: "purple",
    priceRub100: "32.0",
    priceEuro: "0.32",
    priceRub95: "30.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Anita Witzier",
    size: "12/+",
    color: "red",
    priceRub100: "29.9",
    priceEuro: "0.30",
    priceRub95: "28.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Annaconda",
    size: "11/12",
    color: "pink",
    priceRub100: "36.3",
    priceEuro: "0.36",
    priceRub95: "34.5",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Annaconda",
    size: "12/+",
    color: "pink",
    priceRub100: "38.0",
    priceEuro: "0.38",
    priceRub95: "36.1",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Antarctica Fire",
    size: "12/+",
    color: "red",
    priceRub100: "31.6",
    priceEuro: "0.32",
    priceRub95: "30.0",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Antartica Yellow",
    size: "12/+",
    color: "yellow",
    priceRub100: "31.6",
    priceEuro: "0.32",
    priceRub95: "30.0",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Antonov",
    size: "11/12",
    color: "white",
    priceRub100: "32.8",
    priceEuro: "0.33",
    priceRub95: "31.2",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Antonov",
    size: "12/+",
    color: "white",
    priceRub100: "38.5",
    priceEuro: "0.39",
    priceRub95: "36.6",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Aphrodite",
    size: "12/+",
    color: "red",
    priceRub100: "28.1",
    priceEuro: "0.28",
    priceRub95: "26.7",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Argos",
    size: "11/12",
    color: "pink",
    priceRub100: "33.0",
    priceEuro: "0.33",
    priceRub95: "31.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Argos",
    size: "12/+",
    color: "pink",
    priceRub100: "35.0",
    priceEuro: "0.35",
    priceRub95: "33.3",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Asian Beauty",
    size: "12/+",
    color: "red",
    priceRub100: "36.0",
    priceEuro: "0.36",
    priceRub95: "34.2",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Asian Love",
    size: "11/12",
    color: "pink",
    priceRub100: "29.4",
    priceEuro: "0.29",
    priceRub95: "27.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Asian Love",
    size: "12/+",
    color: "pink",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Athena",
    size: "12/+",
    color: "Pink/White",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Atlas",
    size: "12/+",
    color: "red/yellow",
    priceRub100: "35.1",
    priceEuro: "0.35",
    priceRub95: "33.3",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Auxerre",
    size: "12/+",
    color: "pink/white",
    priceRub100: "32.5",
    priceEuro: "0.32",
    priceRub95: "30.8",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Avant Garde",
    size: "12/+",
    color: "creme",
    priceRub100: "36.0",
    priceEuro: "0.36",
    priceRub95: "34.2",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Avocado",
    size: "12/+",
    color: "creme",
    priceRub100: "34.0",
    priceEuro: "0.34",
    priceRub95: "32.3",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Ballgame",
    size: "12/+",
    color: "red",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Barcelona",
    size: "12/+",
    color: "pink",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Barcelona Beach",
    size: "12/+",
    color: "salmon",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Barcelona Beauty",
    size: "12/+",
    color: "pink",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Barcelona Blanca",
    size: "12/+",
    color: "white",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Barcelona Candy",
    size: "12/+",
    color: "light pink",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Barre Alta",
    size: "12/+",
    color: "pink",
    priceRub100: "31.6",
    priceEuro: "0.32",
    priceRub95: "30.0",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Beautytrend",
    size: "11/12",
    color: "white/red",
    priceRub100: "28.0",
    priceEuro: "0.28",
    priceRub95: "26.6",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Beautytrend",
    size: "12/+",
    color: "white/red",
    priceRub100: "32.0",
    priceEuro: "0.32",
    priceRub95: "30.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Beloega",
    size: "12/+",
    color: "white",
    priceRub100: "38.5",
    priceEuro: "0.39",
    priceRub95: "36.6",
  },
  {
    group: "Tulipa",
    sort: "dfr",
    name: "Bendigo",
    size: "11/12",
    color: "red",
    priceRub100: "33.0",
    priceEuro: "0.33",
    priceRub95: "31.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Blenda Flame ( Caramba )",
    size: "12/+",
    color: "white/purple",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Blush",
    size: "12/+",
    color: "red/yellow",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Bob Marley",
    size: "12/+",
    color: "red/yellow",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Bodybuilder",
    size: "12/+",
    color: "red/yellow",
    priceRub100: "32.5",
    priceEuro: "0.32",
    priceRub95: "30.8",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Bolroyal Pink",
    size: "12/+",
    color: "pink",
    priceRub100: "32.5",
    priceEuro: "0.32",
    priceRub95: "30.8",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Bonaire",
    size: "12/+",
    color: "pink",
    priceRub100: "40.2",
    priceEuro: "0.40",
    priceRub95: "38.2",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Brindisi",
    size: "12/+",
    color: "pink",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "dfr",
    name: "Brisbane",
    size: "11/12",
    color: "red/yellow",
    priceRub100: "33.0",
    priceEuro: "0.33",
    priceRub95: "31.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Buckingham",
    size: "11/12",
    color: "yellow/red",
    priceRub100: "32.8",
    priceEuro: "0.33",
    priceRub95: "31.2",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Buckingham",
    size: "12/+",
    color: "yellow/red",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Bullit",
    size: "12/+",
    color: "purple",
    priceRub100: "32.0",
    priceEuro: "0.32",
    priceRub95: "30.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Buster",
    size: "12/+",
    color: "red/yellow",
    priceRub100: "28.1",
    priceEuro: "0.28",
    priceRub95: "26.7",
  },
  {
    group: "Tulipa",
    sort: "pa",
    name: "Cabanna",
    size: "12/+",
    color: "pink/white",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Cacharel",
    size: "11/12",
    color: "pink",
    priceRub100: "38.0",
    priceEuro: "0.38",
    priceRub95: "36.1",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Cacharel",
    size: "12/+",
    color: "pink",
    priceRub100: "40.0",
    priceEuro: "0.40",
    priceRub95: "38.0",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Cadans",
    size: "12/+",
    color: "orange",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Cadenza",
    size: "12/+",
    color: "yellow",
    priceRub100: "35.1",
    priceEuro: "0.35",
    priceRub95: "33.3",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Cambridge",
    size: "11/12",
    color: "white",
    priceRub100: "32.8",
    priceEuro: "0.33",
    priceRub95: "31.2",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Cambridge",
    size: "12/+",
    color: "white",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Canberra",
    size: "12/+",
    color: "purple/white",
    priceRub100: "36.0",
    priceEuro: "0.36",
    priceRub95: "34.2",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Candy Prince",
    size: "12/+",
    color: "pink",
    priceRub100: "27.3",
    priceEuro: "0.27",
    priceRub95: "25.9",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Cannonball",
    size: "11/12",
    color: "red/yellow",
    priceRub100: "34.6",
    priceEuro: "0.35",
    priceRub95: "32.8",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Cannonball",
    size: "12/+",
    color: "red/yellow",
    priceRub100: "38.0",
    priceEuro: "0.38",
    priceRub95: "36.1",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Canyon",
    size: "12/+",
    color: "purple",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Carnaval de Nice",
    size: "11/12",
    color: "white/red",
    priceRub100: "30.3",
    priceEuro: "0.30",
    priceRub95: "28.7",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Carola",
    size: "12/+",
    color: "pink",
    priceRub100: "28.1",
    priceEuro: "0.28",
    priceRub95: "26.7",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Cashback",
    size: "12/+",
    color: "red",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Castella",
    size: "11/12",
    color: "purple",
    priceRub100: "34.6",
    priceEuro: "0.35",
    priceRub95: "32.8",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Castella",
    size: "12/+",
    color: "purple",
    priceRub100: "38.5",
    priceEuro: "0.39",
    priceRub95: "36.6",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Chacha",
    size: "12/+",
    color: "red/white",
    priceRub100: "29.9",
    priceEuro: "0.30",
    priceRub95: "28.4",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Championship",
    size: "12/+",
    color: "red/white",
    priceRub100: "36.0",
    priceEuro: "0.36",
    priceRub95: "34.2",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Choice",
    size: "12/+",
    color: "red/yellow",
    priceRub100: "34.0",
    priceEuro: "0.34",
    priceRub95: "32.3",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Circuit",
    size: "12/+",
    color: "pink",
    priceRub100: "30.7",
    priceEuro: "0.31",
    priceRub95: "29.2",
  },
  {
    group: "Tulipa",
    sort: "sl",
    name: "Clearwater",
    size: "12/+",
    color: "white",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "sl",
    name: "Clearwater",
    size: "14/+",
    color: "white",
    priceRub100: "38.0",
    priceEuro: "0.38",
    priceRub95: "36.1",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Cognac",
    size: "12/+",
    color: "purple",
    priceRub100: "38.5",
    priceEuro: "0.39",
    priceRub95: "36.6",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Columbus",
    size: "12/+",
    color: "pink/white",
    priceRub100: "32.4",
    priceEuro: "0.32",
    priceRub95: "30.8",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Concorde",
    size: "11/12",
    color: "red/white",
    priceRub100: "32.8",
    priceEuro: "0.33",
    priceRub95: "31.2",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Concorde",
    size: "12/+",
    color: "red/white",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Congo",
    size: "11/12",
    color: "yellow/orange",
    priceRub100: "31.1",
    priceEuro: "0.31",
    priceRub95: "29.6",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Congo",
    size: "12/+",
    color: "yellow/orange",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Creme Fraiche",
    size: "12/+",
    color: "creme",
    priceRub100: "34.0",
    priceEuro: "0.34",
    priceRub95: "32.3",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Creme Silence",
    size: "11/12",
    color: "creme",
    priceRub100: "29.4",
    priceEuro: "0.29",
    priceRub95: "27.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Creme Silence",
    size: "12/+",
    color: "creme",
    priceRub100: "36.0",
    priceEuro: "0.36",
    priceRub95: "34.2",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Cricko",
    size: "12/+",
    color: "white",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Crossfire",
    size: "12/+",
    color: "red/yellow",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Crossover",
    size: "12/+",
    color: "pink/white",
    priceRub100: "41.1",
    priceEuro: "0.41",
    priceRub95: "39.1",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Crown of Dynasty",
    size: "12/+",
    color: "pink/white",
    priceRub100: "40.2",
    priceEuro: "0.40",
    priceRub95: "38.2",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Curly Sue",
    size: "12/+",
    color: "purple",
    priceRub100: "29.9",
    priceEuro: "0.30",
    priceRub95: "28.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Curry",
    size: "12/+",
    color: "red",
    priceRub100: "29.9",
    priceEuro: "0.30",
    priceRub95: "28.4",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Dancing Queen",
    size: "11/12",
    color: "yellow",
    priceRub100: "32.8",
    priceEuro: "0.33",
    priceRub95: "31.2",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Dancing Queen",
    size: "12/+",
    color: "yellow",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Danija ( Tanija )",
    size: "12/+",
    color: "purple/white",
    priceRub100: "29.9",
    priceEuro: "0.30",
    priceRub95: "28.4",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Dark Soul",
    size: "11/12",
    color: "purple",
    priceRub100: "29.4",
    priceEuro: "0.29",
    priceRub95: "27.9",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Dark Soul",
    size: "12/+",
    color: "purple",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Davenport",
    size: "12/+",
    color: "red/yellow",
    priceRub100: "31.0",
    priceEuro: "0.31",
    priceRub95: "29.5",
  },
  {
    group: "Tulipa",
    sort: "pa",
    name: "Dee Jay Parrot",
    size: "11/12",
    color: "red/yellow",
    priceRub100: "32.8",
    priceEuro: "0.33",
    priceRub95: "31.2",
  },
  {
    group: "Tulipa",
    sort: "pa",
    name: "Dee Jay Parrot",
    size: "12/+",
    color: "red/yellow",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Delta Chic",
    size: "12/+",
    color: "pink/white",
    priceRub100: "31.6",
    priceEuro: "0.32",
    priceRub95: "30.0",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Delta White",
    size: "12/+",
    color: "white",
    priceRub100: "39.4",
    priceEuro: "0.39",
    priceRub95: "37.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Denmark",
    size: "12/+",
    color: "red/yellow",
    priceRub100: "29.5",
    priceEuro: "0.29",
    priceRub95: "28.0",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Denver",
    size: "12/+",
    color: "red/yellow",
    priceRub100: "30.7",
    priceEuro: "0.31",
    priceRub95: "29.2",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Desirelle",
    size: "12/+",
    color: "pink",
    priceRub100: "38.5",
    priceEuro: "0.39",
    priceRub95: "36.6",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Disco",
    size: "12/+",
    color: "red/yellow",
    priceRub100: "29.0",
    priceEuro: "0.29",
    priceRub95: "27.6",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Donatello",
    size: "12/+",
    color: "white/pink",
    priceRub100: "36.0",
    priceEuro: "0.36",
    priceRub95: "34.2",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Dotcom (Vika Rosa)",
    size: "11/12",
    color: "pink/white",
    priceRub100: "32.8",
    priceEuro: "0.33",
    priceRub95: "31.2",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Dotcom (Vika Rosa)",
    size: "12/+",
    color: "pink/white",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Double Price",
    size: "11/12",
    color: "pink",
    priceRub100: "33.0",
    priceEuro: "0.33",
    priceRub95: "31.4",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Double Price",
    size: "12/+",
    color: "pink",
    priceRub100: "38.0",
    priceEuro: "0.38",
    priceRub95: "36.1",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Double Trouble",
    size: "12/+",
    color: "yellow",
    priceRub100: "38.2",
    priceEuro: "0.38",
    priceRub95: "36.3",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Dreamer",
    size: "11/12",
    color: "pink",
    priceRub100: "45.0",
    priceEuro: "0.45",
    priceRub95: "42.8",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Dreamer",
    size: "12/+",
    color: "pink",
    priceRub100: "49.0",
    priceEuro: "0.49",
    priceRub95: "46.6",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Dressing",
    size: "12/+",
    color: "pink",
    priceRub100: "39.6",
    priceEuro: "0.40",
    priceRub95: "37.6",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Duchess",
    size: "12/+",
    color: "white",
    priceRub100: "37.8",
    priceEuro: "0.38",
    priceRub95: "35.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Dutch Beauty",
    size: "11/12",
    color: "pink",
    priceRub100: "29.4",
    priceEuro: "0.29",
    priceRub95: "27.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Dutch Beauty",
    size: "12/+",
    color: "pink",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Dutch Design",
    size: "12/+",
    color: "red/white",
    priceRub100: "29.0",
    priceEuro: "0.29",
    priceRub95: "27.6",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Dutch Mountain",
    size: "12/+",
    color: "white",
    priceRub100: "34.0",
    priceEuro: "0.34",
    priceRub95: "32.3",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Dutching",
    size: "12/+",
    color: "orange",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Dynamo",
    size: "11/12",
    color: "red",
    priceRub100: "29.4",
    priceEuro: "0.29",
    priceRub95: "27.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Dynamo",
    size: "12/+",
    color: "red",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Edition",
    size: "12/+",
    color: "red/yellow",
    priceRub100: "35.1",
    priceEuro: "0.35",
    priceRub95: "33.3",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Etched Salmon",
    size: "12/+",
    color: "pink",
    priceRub100: "45.0",
    priceEuro: "0.45",
    priceRub95: "42.8",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Everton",
    size: "12/+",
    color: "red/white",
    priceRub100: "40.2",
    priceEuro: "0.40",
    priceRub95: "38.2",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Exotic Sun",
    size: "12/+",
    color: "yellow",
    priceRub100: "38.5",
    priceEuro: "0.39",
    priceRub95: "36.6",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Expression",
    size: "11/12",
    color: "pink",
    priceRub100: "32.0",
    priceEuro: "0.32",
    priceRub95: "30.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Expression",
    size: "12/+",
    color: "pink",
    priceRub100: "36.0",
    priceEuro: "0.36",
    priceRub95: "34.2",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Fabio",
    size: "12/+",
    color: "red/yellow",
    priceRub100: "28.0",
    priceEuro: "0.28",
    priceRub95: "26.6",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Finola",
    size: "12/+",
    color: "pink/white",
    priceRub100: "30.1",
    priceEuro: "0.30",
    priceRub95: "28.6",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "First Date",
    size: "12/+",
    color: "pink",
    priceRub100: "32.0",
    priceEuro: "0.32",
    priceRub95: "30.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "First Life",
    size: "12/+",
    color: "purple/pink",
    priceRub100: "30.0",
    priceEuro: "0.30",
    priceRub95: "28.5",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "First Price",
    size: "11/12",
    color: "red",
    priceRub100: "32.0",
    priceEuro: "0.32",
    priceRub95: "30.4",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "First Price",
    size: "12/+",
    color: "red",
    priceRub100: "35.9",
    priceEuro: "0.36",
    priceRub95: "34.1",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "First Star",
    size: "12/+",
    color: "red",
    priceRub100: "32.0",
    priceEuro: "0.32",
    priceRub95: "30.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Florence",
    size: "12/+",
    color: "pink/white",
    priceRub100: "34.2",
    priceEuro: "0.34",
    priceRub95: "32.5",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Fortress",
    size: "11/12",
    color: "purple",
    priceRub100: "27.8",
    priceEuro: "0.28",
    priceRub95: "26.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Fortress",
    size: "12/+",
    color: "purple",
    priceRub100: "31.6",
    priceEuro: "0.32",
    priceRub95: "30.0",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Foxtrot",
    size: "12/+",
    color: "pink",
    priceRub100: "32.0",
    priceEuro: "0.32",
    priceRub95: "30.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Freewheeler",
    size: "12/+",
    color: "white",
    priceRub100: "36.0",
    priceEuro: "0.36",
    priceRub95: "34.2",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Fringed Purple/White",
    size: "12/+",
    color: "purple/white",
    priceRub100: "35.1",
    priceEuro: "0.35",
    priceRub95: "33.3",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Fun for Two",
    size: "12/+",
    color: "creme",
    priceRub100: "38.5",
    priceEuro: "0.39",
    priceRub95: "36.6",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Fun for Two Yellow",
    size: "11/12",
    color: "yellow",
    priceRub100: "32.8",
    priceEuro: "0.33",
    priceRub95: "31.2",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Fun for Two Yellow",
    size: "12/+",
    color: "yellow",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Gabriella",
    size: "11/12",
    color: "pink",
    priceRub100: "29.0",
    priceEuro: "0.29",
    priceRub95: "27.6",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Gabriella",
    size: "12/+",
    color: "pink",
    priceRub100: "34.0",
    priceEuro: "0.34",
    priceRub95: "32.3",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Gala crispa white",
    size: "11/12",
    color: "white",
    priceRub100: "36.3",
    priceEuro: "0.36",
    priceRub95: "34.5",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Gala crispa white",
    size: "12/+",
    color: "white",
    priceRub100: "40.2",
    priceEuro: "0.40",
    priceRub95: "38.2",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Galileo",
    size: "11/12",
    color: "white",
    priceRub100: "32.8",
    priceEuro: "0.33",
    priceRub95: "31.2",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Galileo",
    size: "12/+",
    color: "white",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Geneva",
    size: "11/12",
    color: "orange",
    priceRub100: "31.1",
    priceEuro: "0.31",
    priceRub95: "29.6",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Geneva",
    size: "12/+",
    color: "orange",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Ghost Town",
    size: "12/+",
    color: "purple",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Gomera",
    size: "12/+",
    color: "purple",
    priceRub100: "29.9",
    priceEuro: "0.30",
    priceRub95: "28.4",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Gorilla",
    size: "12/+",
    color: "purple",
    priceRub100: "29.9",
    priceEuro: "0.30",
    priceRub95: "28.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Grand Perfection",
    size: "12/+",
    color: "yellow/red",
    priceRub100: "25.5",
    priceEuro: "0.26",
    priceRub95: "24.3",
  },
  {
    group: "Tulipa",
    sort: "dh",
    name: "Hakuun",
    size: "12/+",
    color: "white",
    priceRub100: "32.0",
    priceEuro: "0.32",
    priceRub95: "30.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Happy Generation",
    size: "12/+",
    color: "white/red",
    priceRub100: "26.0",
    priceEuro: "0.26",
    priceRub95: "24.7",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Hashtag",
    size: "12/+",
    color: "pink",
    priceRub100: "38.5",
    priceEuro: "0.39",
    priceRub95: "36.6",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Hawaii ( Super Siesta )",
    size: "11/12",
    color: "pink/white",
    priceRub100: "36.3",
    priceEuro: "0.36",
    priceRub95: "34.5",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Hawaii ( Super Siesta )",
    size: "12/+",
    color: "pink/white",
    priceRub100: "38.9",
    priceEuro: "0.39",
    priceRub95: "37.0",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Heart Beat",
    size: "12/+",
    color: "pink",
    priceRub100: "38.0",
    priceEuro: "0.38",
    priceRub95: "36.1",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Heartbreaker",
    size: "11/12",
    color: "red",
    priceRub100: "29.4",
    priceEuro: "0.29",
    priceRub95: "27.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Heartbreaker",
    size: "12/+",
    color: "red",
    priceRub100: "32.1",
    priceEuro: "0.32",
    priceRub95: "30.5",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Heavy Duty",
    size: "12/+",
    color: "pink/yellow",
    priceRub100: "31.6",
    priceEuro: "0.32",
    priceRub95: "30.0",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Hema",
    size: "12/+",
    color: "red/white",
    priceRub100: "33.0",
    priceEuro: "0.33",
    priceRub95: "31.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Hennie v.d. Most",
    size: "12/+",
    color: "red/yellow",
    priceRub100: "32.0",
    priceEuro: "0.32",
    priceRub95: "30.4",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Honeymoon",
    size: "12/+",
    color: "white",
    priceRub100: "34.0",
    priceEuro: "0.34",
    priceRub95: "32.3",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Horizon Red-Yellow",
    size: "11/12",
    color: "red/yellow",
    priceRub100: "32.8",
    priceEuro: "0.33",
    priceRub95: "31.2",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Horizon Red-Yellow",
    size: "12/+",
    color: "red/yellow",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Hotspot",
    size: "12/+",
    color: "red",
    priceRub100: "33.0",
    priceEuro: "0.33",
    priceRub95: "31.4",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Huis ten Bosch",
    size: "12/+",
    color: "pink",
    priceRub100: "28.0",
    priceEuro: "0.28",
    priceRub95: "26.6",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Ice Cap",
    size: "12/+",
    color: "white",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Ice Rif",
    size: "12/+",
    color: "white",
    priceRub100: "38.0",
    priceEuro: "0.38",
    priceRub95: "36.1",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Iceberg",
    size: "11/12",
    color: "white",
    priceRub100: "32.8",
    priceEuro: "0.33",
    priceRub95: "31.2",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Iceberg",
    size: "12/+",
    color: "white",
    priceRub100: "38.0",
    priceEuro: "0.38",
    priceRub95: "36.1",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Icoon",
    size: "12/+",
    color: "orange",
    priceRub100: "30.4",
    priceEuro: "0.30",
    priceRub95: "28.9",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Indiana",
    size: "12/+",
    color: "red",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Innocence",
    size: "12/+",
    color: "red/white",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Jakoetsk",
    size: "12/+",
    color: "white",
    priceRub100: "38.5",
    priceEuro: "0.39",
    priceRub95: "36.6",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Jan Buis",
    size: "12/+",
    color: "red/white",
    priceRub100: "29.9",
    priceEuro: "0.30",
    priceRub95: "28.4",
  },
  {
    group: "Tulipa",
    sort: "sl",
    name: "Jetstream",
    size: "12/+",
    color: "pink",
    priceRub100: "34.0",
    priceEuro: "0.34",
    priceRub95: "32.3",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Jumbo Pink",
    size: "12/+",
    color: "pink",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Kadima",
    size: "12/+",
    color: "pink/white",
    priceRub100: "29.9",
    priceEuro: "0.30",
    priceRub95: "28.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Kamaliya",
    size: "12/+",
    color: "purple/white",
    priceRub100: "28.0",
    priceEuro: "0.28",
    priceRub95: "26.6",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Katinka",
    size: "11/12",
    color: "lila",
    priceRub100: "36.0",
    priceEuro: "0.36",
    priceRub95: "34.2",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Katinka",
    size: "12/+",
    color: "lila",
    priceRub100: "39.5",
    priceEuro: "0.40",
    priceRub95: "37.6",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Kick Start",
    size: "11/12",
    color: "lilac",
    priceRub100: "29.4",
    priceEuro: "0.29",
    priceRub95: "27.9",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Kick Start",
    size: "12/+",
    color: "lila",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Killing Love",
    size: "12/+",
    color: "red",
    priceRub100: "33.0",
    priceEuro: "0.33",
    priceRub95: "31.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Kisha",
    size: "12/+",
    color: "pink",
    priceRub100: "29.9",
    priceEuro: "0.30",
    priceRub95: "28.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Krissi",
    size: "12/+",
    color: "pink",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Kung Fu",
    size: "12/+",
    color: "red/white",
    priceRub100: "29.9",
    priceEuro: "0.30",
    priceRub95: "28.4",
  },
  {
    group: "Tulipa",
    sort: "dfr",
    name: "La Mour",
    size: "12/+",
    color: "red",
    priceRub100: "39.4",
    priceEuro: "0.39",
    priceRub95: "37.5",
  },
  {
    group: "Tulipa",
    sort: "dh",
    name: "Lalibela",
    size: "12/+",
    color: "red",
    priceRub100: "27.9",
    priceEuro: "0.28",
    priceRub95: "26.5",
  },
  {
    group: "Tulipa",
    sort: "dh",
    name: "Lalibela",
    size: "14/+",
    color: "red",
    priceRub100: "30.7",
    priceEuro: "0.31",
    priceRub95: "29.2",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Laptop",
    size: "12/+",
    color: "purple",
    priceRub100: "29.9",
    priceEuro: "0.30",
    priceRub95: "28.4",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Largo",
    size: "12/+",
    color: "red",
    priceRub100: "35.1",
    priceEuro: "0.35",
    priceRub95: "33.3",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Lech Walesa",
    size: "12/+",
    color: "red/white",
    priceRub100: "32.4",
    priceEuro: "0.32",
    priceRub95: "30.8",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Librije",
    size: "11,5-14",
    color: "purple/white",
    priceRub100: "27.7",
    priceEuro: "0.28",
    priceRub95: "26.3",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Librije",
    size: "12/+",
    color: "purple/white",
    priceRub100: "31.6",
    priceEuro: "0.32",
    priceRub95: "30.0",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Limerick",
    size: "12/+",
    color: "red",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Lincoln",
    size: "12/+",
    color: "pink",
    priceRub100: "32.0",
    priceEuro: "0.32",
    priceRub95: "30.4",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Lingerie",
    size: "12/+",
    color: "pink/white",
    priceRub100: "40.2",
    priceEuro: "0.40",
    priceRub95: "38.2",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Lion's Glory",
    size: "12/+",
    color: "yellow",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Lipstick",
    size: "12/+",
    color: "pink",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Lorenzo",
    size: "12/+",
    color: "orange",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Lornah",
    size: "11/12",
    color: "red/white",
    priceRub100: "25.1",
    priceEuro: "0.25",
    priceRub95: "23.8",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Lornah",
    size: "12/+",
    color: "red/white",
    priceRub100: "29.0",
    priceEuro: "0.29",
    priceRub95: "27.6",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Louvre",
    size: "12/+",
    color: "purple",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Loyalty",
    size: "11/12",
    color: "pink",
    priceRub100: "29.4",
    priceEuro: "0.29",
    priceRub95: "27.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Loyalty",
    size: "12/+",
    color: "pink",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Luba",
    size: "12/+",
    color: "red/yellow",
    priceRub100: "28.1",
    priceEuro: "0.28",
    priceRub95: "26.7",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Maitresse",
    size: "11/12",
    color: "pink",
    priceRub100: "35.7",
    priceEuro: "0.36",
    priceRub95: "33.9",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Maitresse",
    size: "12/+",
    color: "pink",
    priceRub100: "39.8",
    priceEuro: "0.40",
    priceRub95: "37.8",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Malaysia",
    size: "12/+",
    color: "creme",
    priceRub100: "36.0",
    priceEuro: "0.36",
    priceRub95: "34.2",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Mango Charm",
    size: "12/+",
    color: "salmon",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Marax Pride",
    size: "12/+",
    color: "red/yellow",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Mariage",
    size: "11/12",
    color: "pink",
    priceRub100: "35.7",
    priceEuro: "0.36",
    priceRub95: "33.9",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Mariage",
    size: "12/+",
    color: "pink",
    priceRub100: "39.5",
    priceEuro: "0.39",
    priceRub95: "37.5",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Marie Jo",
    size: "12/+",
    color: "yellow",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "pa",
    name: "Marvel Parrot",
    size: "11/12",
    color: "pink",
    priceRub100: "36.3",
    priceEuro: "0.36",
    priceRub95: "34.5",
  },
  {
    group: "Tulipa",
    sort: "pa",
    name: "Marvel Parrot",
    size: "12/+",
    color: "pink",
    priceRub100: "40.2",
    priceEuro: "0.40",
    priceRub95: "38.2",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Masha",
    size: "12/+",
    color: "red/yellow",
    priceRub100: "29.9",
    priceEuro: "0.30",
    priceRub95: "28.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Match",
    size: "12/+",
    color: "yellow/red",
    priceRub100: "29.0",
    priceEuro: "0.29",
    priceRub95: "27.6",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Matchmaker",
    size: "11/12",
    color: "pink",
    priceRub100: "32.8",
    priceEuro: "0.33",
    priceRub95: "31.2",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Memphis",
    size: "12/+",
    color: "pink/white",
    priceRub100: "32.5",
    priceEuro: "0.32",
    priceRub95: "30.8",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Mikado",
    size: "12/+",
    color: "red",
    priceRub100: "31.6",
    priceEuro: "0.32",
    priceRub95: "30.0",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Milkshake",
    size: "12/+",
    color: "pink",
    priceRub100: "37.1",
    priceEuro: "0.37",
    priceRub95: "35.3",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Miller Time",
    size: "12/+",
    color: "yellow",
    priceRub100: "31.6",
    priceEuro: "0.32",
    priceRub95: "30.0",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Minsk",
    size: "11/12",
    color: "red/yellow",
    priceRub100: "32.0",
    priceEuro: "0.32",
    priceRub95: "30.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Minsk",
    size: "12/+",
    color: "red/yellow",
    priceRub100: "36.0",
    priceEuro: "0.36",
    priceRub95: "34.2",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Mira",
    size: "11/12",
    color: "Red",
    priceRub100: "32.8",
    priceEuro: "0.33",
    priceRub95: "31.2",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Mondial",
    size: "12/+",
    color: "white",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Mondiano",
    size: "12/+",
    color: "red",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Mumbai",
    size: "12/+",
    color: "pink",
    priceRub100: "38.5",
    priceEuro: "0.39",
    priceRub95: "36.6",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Neglige",
    size: "11/12",
    color: "pink/white",
    priceRub100: "32.8",
    priceEuro: "0.33",
    priceRub95: "31.2",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Neglige",
    size: "12/+",
    color: "white/pink",
    priceRub100: "36.0",
    priceEuro: "0.36",
    priceRub95: "34.2",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Negrita double",
    size: "12/+",
    color: "purple",
    priceRub100: "29.9",
    priceEuro: "0.30",
    priceRub95: "28.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Nepal",
    size: "Z11,75-OP",
    color: "white",
    priceRub100: "38.0",
    priceEuro: "0.38",
    priceRub95: "36.1",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "New Santa",
    size: "12/+",
    color: "red/white",
    priceRub100: "32.0",
    priceEuro: "0.32",
    priceRub95: "30.4",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Nikon",
    size: "11/12",
    color: "yellow",
    priceRub100: "34.6",
    priceEuro: "0.35",
    priceRub95: "32.8",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Nikon",
    size: "12/+",
    color: "yellow",
    priceRub100: "38.5",
    priceEuro: "0.39",
    priceRub95: "36.6",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Northcap",
    size: "11/12",
    color: "white",
    priceRub100: "34.0",
    priceEuro: "0.34",
    priceRub95: "32.3",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Northcap",
    size: "12/+",
    color: "white",
    priceRub100: "39.0",
    priceEuro: "0.39",
    priceRub95: "37.0",
  },
  {
    group: "Tulipa",
    sort: "dh",
    name: "Novi Sun",
    size: "12/+",
    color: "yellow",
    priceRub100: "27.9",
    priceEuro: "0.28",
    priceRub95: "26.5",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Obsession",
    size: "12/+",
    color: "pink",
    priceRub100: "37.3",
    priceEuro: "0.37",
    priceRub95: "35.4",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Orange Passion",
    size: "11/12",
    color: "orange",
    priceRub100: "32.8",
    priceEuro: "0.33",
    priceRub95: "31.2",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Orange Passion",
    size: "12/+",
    color: "orange",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Orange Sherpa",
    size: "12/+",
    color: "orange",
    priceRub100: "31.6",
    priceEuro: "0.32",
    priceRub95: "30.0",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Ozon",
    size: "12/+",
    color: "purple",
    priceRub100: "31.6",
    priceEuro: "0.32",
    priceRub95: "30.0",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Pacha",
    size: "12/+",
    color: "red",
    priceRub100: "30.7",
    priceEuro: "0.31",
    priceRub95: "29.2",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Pallada",
    size: "12/+",
    color: "red",
    priceRub100: "27.3",
    priceEuro: "0.27",
    priceRub95: "25.9",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Palmyra",
    size: "12/+",
    color: "black",
    priceRub100: "35.1",
    priceEuro: "0.35",
    priceRub95: "33.3",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Pamplona",
    size: "12/+",
    color: "red",
    priceRub100: "34.0",
    priceEuro: "0.34",
    priceRub95: "32.3",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Panama",
    size: "12/+",
    color: "pink",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Paradero",
    size: "11/12",
    color: "pink",
    priceRub100: "29.4",
    priceEuro: "0.29",
    priceRub95: "27.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Paul Mc Cartney",
    size: "12/+",
    color: "red/white",
    priceRub100: "35.1",
    priceEuro: "0.35",
    priceRub95: "33.3",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Pearl Harbour",
    size: "12/+",
    color: "red",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "dfr",
    name: "Perth",
    size: "11/12",
    color: "pink",
    priceRub100: "33.0",
    priceEuro: "0.33",
    priceRub95: "31.4",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Perugia",
    size: "12/+",
    color: "yellow/red",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Pescara",
    size: "11/12",
    color: "pink",
    priceRub100: "34.0",
    priceEuro: "0.34",
    priceRub95: "32.3",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Pescara",
    size: "12/+",
    color: "pink",
    priceRub100: "38.3",
    priceEuro: "0.38",
    priceRub95: "36.4",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Phantom",
    size: "12/+",
    color: "yellow/red",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Philly Belle",
    size: "11/12",
    color: "yellow",
    priceRub100: "32.8",
    priceEuro: "0.33",
    priceRub95: "31.2",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Philly Belle",
    size: "12/+",
    color: "red",
    priceRub100: "36.0",
    priceEuro: "0.36",
    priceRub95: "34.2",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Pink Ardour",
    size: "12/+",
    color: "pink",
    priceRub100: "28.7",
    priceEuro: "0.29",
    priceRub95: "27.2",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Pink Delight",
    size: "11/12",
    color: "pink",
    priceRub100: "32.8",
    priceEuro: "0.33",
    priceRub95: "31.2",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Pink Delight",
    size: "12/+",
    color: "pink",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "dh",
    name: "Pink Impression",
    size: "12/+",
    color: "pink",
    priceRub100: "24.7",
    priceEuro: "0.25",
    priceRub95: "23.4",
  },
  {
    group: "Tulipa",
    sort: "dh",
    name: "Pink Impression",
    size: "14/+",
    color: "pink",
    priceRub100: "27.4",
    priceEuro: "0.27",
    priceRub95: "26.1",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Pink Marlene",
    size: "11/12",
    color: "pink",
    priceRub100: "30.3",
    priceEuro: "0.30",
    priceRub95: "28.7",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Pink Marlene",
    size: "12/+",
    color: "pink",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Pink Mist",
    size: "12/+",
    color: "pink",
    priceRub100: "45.0",
    priceEuro: "0.45",
    priceRub95: "42.8",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Piste X",
    size: "11/12",
    color: "creme",
    priceRub100: "29.4",
    priceEuro: "0.29",
    priceRub95: "27.9",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Piste X",
    size: "12/+",
    color: "creme",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Polar Bear",
    size: "12/+",
    color: "white",
    priceRub100: "38.7",
    priceEuro: "0.39",
    priceRub95: "36.8",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Polestar",
    size: "11/12",
    color: "white",
    priceRub100: "39.0",
    priceEuro: "0.39",
    priceRub95: "37.1",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Polestar",
    size: "12/+",
    color: "white",
    priceRub100: "45.0",
    priceEuro: "0.45",
    priceRub95: "42.8",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Pontiac",
    size: "11/12",
    color: "purple",
    priceRub100: "29.4",
    priceEuro: "0.29",
    priceRub95: "27.9",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Pontiac",
    size: "12/+",
    color: "purple",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Poseidon",
    size: "12/+",
    color: "red/white",
    priceRub100: "36.0",
    priceEuro: "0.36",
    priceRub95: "34.2",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Power Play",
    size: "12/+",
    color: "red/yellow",
    priceRub100: "29.9",
    priceEuro: "0.30",
    priceRub95: "28.4",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Presto",
    size: "12/+",
    color: "red",
    priceRub100: "35.1",
    priceEuro: "0.35",
    priceRub95: "33.3",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Prime Time",
    size: "12/+",
    color: "pink",
    priceRub100: "38.5",
    priceEuro: "0.39",
    priceRub95: "36.6",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Pulitzer",
    size: "11/12",
    color: "pink/white",
    priceRub100: "29.4",
    priceEuro: "0.29",
    priceRub95: "27.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Pulitzer",
    size: "12/+",
    color: "pink/white",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Purple Crystal",
    size: "12/+",
    color: "purple",
    priceRub100: "29.9",
    priceEuro: "0.30",
    priceRub95: "28.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Purple Flag",
    size: "12/+",
    color: "purple",
    priceRub100: "27.3",
    priceEuro: "0.27",
    priceRub95: "25.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Purple Lord",
    size: "11/12",
    color: "purple",
    priceRub100: "32.0",
    priceEuro: "0.32",
    priceRub95: "30.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Purple Lord",
    size: "12/+",
    color: "purple",
    priceRub100: "35.1",
    priceEuro: "0.35",
    priceRub95: "33.3",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Purple Master",
    size: "12/+",
    color: "purple",
    priceRub100: "29.9",
    priceEuro: "0.30",
    priceRub95: "28.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Purple Prince",
    size: "12/+",
    color: "purple",
    priceRub100: "26.4",
    priceEuro: "0.26",
    priceRub95: "25.1",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Purple Sky",
    size: "12/+",
    color: "purple",
    priceRub100: "33.0",
    priceEuro: "0.33",
    priceRub95: "31.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Purple Valley",
    size: "12/+",
    color: "purple",
    priceRub100: "31.0",
    priceEuro: "0.31",
    priceRub95: "29.5",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Queensday",
    size: "12/+",
    color: "orange",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "dfr",
    name: "Queensland",
    size: "11/12",
    color: "red/white",
    priceRub100: "33.0",
    priceEuro: "0.33",
    priceRub95: "31.4",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Quinty trustfull",
    size: "11/12",
    color: "pink",
    priceRub100: "39.0",
    priceEuro: "0.39",
    priceRub95: "37.1",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Quinty trustfull",
    size: "12/+",
    color: "pink",
    priceRub100: "45.0",
    priceEuro: "0.45",
    priceRub95: "42.8",
  },
  {
    group: "Tulipa",
    sort: "pa",
    name: "Rasta Parrot",
    size: "12/+",
    color: "yellow/red",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Ready",
    size: "11/12",
    color: "red/yellow",
    priceRub100: "32.8",
    priceEuro: "0.33",
    priceRub95: "31.2",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Ready",
    size: "12/+",
    color: "red/yellow",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Rebellious Yellow",
    size: "11/12",
    color: "yellow",
    priceRub100: "32.8",
    priceEuro: "0.33",
    priceRub95: "31.2",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Rebellious Yellow",
    size: "12/+",
    color: "yellow",
    priceRub100: "36.0",
    priceEuro: "0.36",
    priceRub95: "34.2",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Red Angel",
    size: "12/+",
    color: "red",
    priceRub100: "29.0",
    priceEuro: "0.29",
    priceRub95: "27.6",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Red Dress",
    size: "11/12",
    color: "red",
    priceRub100: "32.8",
    priceEuro: "0.33",
    priceRub95: "31.2",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Red Dress",
    size: "12/+",
    color: "red",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Red Gold",
    size: "12/+",
    color: "red",
    priceRub100: "31.0",
    priceEuro: "0.31",
    priceRub95: "29.5",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Red Horizon",
    size: "11/12",
    color: "red",
    priceRub100: "32.8",
    priceEuro: "0.33",
    priceRub95: "31.2",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Red Horizon",
    size: "12/+",
    color: "red",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "dh",
    name: "Red Impression",
    size: "14/+",
    color: "red",
    priceRub100: "24.7",
    priceEuro: "0.25",
    priceRub95: "23.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Red Stone",
    size: "12/+",
    color: "red",
    priceRub100: "29.9",
    priceEuro: "0.30",
    priceRub95: "28.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Remix",
    size: "12/+",
    color: "white",
    priceRub100: "36.0",
    priceEuro: "0.36",
    priceRub95: "34.2",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Rescue",
    size: "12/+",
    color: "red",
    priceRub100: "28.1",
    priceEuro: "0.28",
    priceRub95: "26.7",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Respectable",
    size: "12/+",
    color: "purple",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Rigel",
    size: "12/+",
    color: "white",
    priceRub100: "39.0",
    priceEuro: "0.39",
    priceRub95: "37.1",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Rococo Double",
    size: "11/12",
    color: "red",
    priceRub100: "29.4",
    priceEuro: "0.29",
    priceRub95: "27.9",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Rococo Double",
    size: "12/+",
    color: "red",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Rodeo Drive",
    size: "12/+",
    color: "red",
    priceRub100: "27.0",
    priceEuro: "0.27",
    priceRub95: "25.7",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Roeska",
    size: "11/12",
    color: "purple",
    priceRub100: "27.7",
    priceEuro: "0.28",
    priceRub95: "26.3",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Roeska",
    size: "12/+",
    color: "purple",
    priceRub100: "32.0",
    priceEuro: "0.32",
    priceRub95: "30.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Roman Empire",
    size: "12/+",
    color: "red/white",
    priceRub100: "34.0",
    priceEuro: "0.34",
    priceRub95: "32.3",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Roman Power",
    size: "11/12",
    color: "red/yellow",
    priceRub100: "29.4",
    priceEuro: "0.29",
    priceRub95: "27.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Roman Power",
    size: "12/+",
    color: "red/yellow",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Ronaldo Unique",
    size: "12/+",
    color: "purple",
    priceRub100: "31.6",
    priceEuro: "0.32",
    priceRub95: "30.0",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Saigon Double",
    size: "11/12",
    color: "purple",
    priceRub100: "32.8",
    priceEuro: "0.33",
    priceRub95: "31.2",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Saigon Double",
    size: "12/+",
    color: "purple",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "dh",
    name: "Salmon Lalibela",
    size: "12/+",
    color: "Salmon",
    priceRub100: "32.5",
    priceEuro: "0.32",
    priceRub95: "30.8",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Salmon Price",
    size: "12/+",
    color: "Salmon",
    priceRub100: "45.0",
    priceEuro: "0.45",
    priceRub95: "42.8",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Sambuca",
    size: "12/+",
    color: "red/white",
    priceRub100: "43.0",
    priceEuro: "0.43",
    priceRub95: "40.9",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "San Christina",
    size: "11/12",
    color: "purple",
    priceRub100: "29.4",
    priceEuro: "0.29",
    priceRub95: "27.9",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "San Christina",
    size: "12/+",
    color: "purple",
    priceRub100: "32.1",
    priceEuro: "0.32",
    priceRub95: "30.5",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "San Clemente",
    size: "11/12",
    color: "purple",
    priceRub100: "29.4",
    priceEuro: "0.29",
    priceRub95: "27.9",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "San Clemente",
    size: "12/+",
    color: "purple",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "San George",
    size: "12/+",
    color: "purple",
    priceRub100: "29.9",
    priceEuro: "0.30",
    priceRub95: "28.4",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "San Leandro",
    size: "11/12",
    color: "pink/white",
    priceRub100: "29.4",
    priceEuro: "0.29",
    priceRub95: "27.9",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "San Leandro",
    size: "12/+",
    color: "pink/white",
    priceRub100: "32.0",
    priceEuro: "0.32",
    priceRub95: "30.4",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "San Luiz",
    size: "11/12",
    color: "purple",
    priceRub100: "29.4",
    priceEuro: "0.29",
    priceRub95: "27.9",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "San Luiz",
    size: "12/+",
    color: "purple",
    priceRub100: "31.0",
    priceEuro: "0.31",
    priceRub95: "29.5",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "San Martin",
    size: "11/12",
    color: "pink/white",
    priceRub100: "29.4",
    priceEuro: "0.29",
    priceRub95: "27.9",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "San Martin",
    size: "12/+",
    color: "pink/white",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "San Pablo",
    size: "11/12",
    color: "red/white",
    priceRub100: "29.4",
    priceEuro: "0.29",
    priceRub95: "27.9",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "San Pablo",
    size: "12/+",
    color: "red/white",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "San Remo",
    size: "11/12",
    color: "pink",
    priceRub100: "38.0",
    priceEuro: "0.38",
    priceRub95: "36.1",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "San Remo",
    size: "12/+",
    color: "pink",
    priceRub100: "42.0",
    priceEuro: "0.42",
    priceRub95: "39.9",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "San Stefano",
    size: "11/12",
    color: "pink/white",
    priceRub100: "29.4",
    priceEuro: "0.29",
    priceRub95: "27.9",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "San Stefano",
    size: "12/+",
    color: "pink/white",
    priceRub100: "32.6",
    priceEuro: "0.33",
    priceRub95: "30.9",
  },
  {
    group: "Tulipa",
    sort: "lf",
    name: "Sanne",
    size: "12/+",
    color: "pink/yellow",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Seadov",
    size: "12/+",
    color: "red",
    priceRub100: "23.8",
    priceEuro: "0.24",
    priceRub95: "22.6",
  },
  {
    group: "Tulipa",
    sort: "pa",
    name: "Seadov Parrot",
    size: "12/+",
    color: "red",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Showdown",
    size: "12/+",
    color: "pink/yellow",
    priceRub100: "29.9",
    priceEuro: "0.30",
    priceRub95: "28.4",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Showroom (Arie)",
    size: "12/+",
    color: "white/red",
    priceRub100: "32.5",
    priceEuro: "0.32",
    priceRub95: "30.8",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Sissi",
    size: "11/12",
    color: "pink",
    priceRub100: "32.5",
    priceEuro: "0.32",
    priceRub95: "30.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Sissi",
    size: "12/+",
    color: "pink",
    priceRub100: "40.4",
    priceEuro: "0.40",
    priceRub95: "38.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Sky Dance",
    size: "11/12",
    color: "red",
    priceRub100: "36.3",
    priceEuro: "0.36",
    priceRub95: "34.5",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Sky Dance",
    size: "12/+",
    color: "red",
    priceRub100: "40.2",
    priceEuro: "0.40",
    priceRub95: "38.2",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Smirnoff",
    size: "12/+",
    color: "white",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Snapshot",
    size: "12/+",
    color: "pink/white",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Sniper",
    size: "11/12",
    color: "Pink",
    priceRub100: "36.0",
    priceEuro: "0.36",
    priceRub95: "34.2",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Sniper",
    size: "12/+",
    color: "pink",
    priceRub100: "39.0",
    priceEuro: "0.39",
    priceRub95: "37.1",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Snowboard",
    size: "12/+",
    color: "white",
    priceRub100: "45.4",
    priceEuro: "0.45",
    priceRub95: "43.2",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Spirit",
    size: "11/12",
    color: "red/yellow",
    priceRub100: "29.4",
    priceEuro: "0.29",
    priceRub95: "27.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Spirit",
    size: "12/+",
    color: "red/yellow",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Spitfire",
    size: "12/+",
    color: "red",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Spot On",
    size: "12/+",
    color: "red",
    priceRub100: "28.1",
    priceEuro: "0.28",
    priceRub95: "26.7",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Stargazer",
    size: "12/+",
    color: "red/white",
    priceRub100: "32.5",
    priceEuro: "0.32",
    priceRub95: "30.8",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Strong Energy",
    size: "12/+",
    color: "red",
    priceRub100: "28.1",
    priceEuro: "0.28",
    priceRub95: "26.7",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Strong Gold",
    size: "11/12",
    color: "yellow",
    priceRub100: "31.0",
    priceEuro: "0.31",
    priceRub95: "29.5",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Strong Gold",
    size: "12/+",
    color: "yellow",
    priceRub100: "31.8",
    priceEuro: "0.32",
    priceRub95: "30.2",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Strong Gold",
    size: "14/+",
    color: "yellow",
    priceRub100: "34.0",
    priceEuro: "0.34",
    priceRub95: "32.3",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Strong Love",
    size: "11/12",
    color: "red",
    priceRub100: "27.7",
    priceEuro: "0.28",
    priceRub95: "26.3",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Strong Love",
    size: "12/+",
    color: "red",
    priceRub100: "29.7",
    priceEuro: "0.30",
    priceRub95: "28.2",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Strong Love",
    size: "14/+",
    color: "red",
    priceRub100: "32.0",
    priceEuro: "0.32",
    priceRub95: "30.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Strong Power",
    size: "12/+",
    color: "red",
    priceRub100: "29.9",
    priceEuro: "0.30",
    priceRub95: "28.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Sunbelt",
    size: "12/+",
    color: "orange",
    priceRub100: "29.9",
    priceEuro: "0.30",
    priceRub95: "28.4",
  },
  {
    group: "Tulipa",
    sort: "pa",
    name: "Super Parrot",
    size: "11/12",
    color: "white",
    priceRub100: "36.3",
    priceEuro: "0.36",
    priceRub95: "34.5",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Supermodel",
    size: "11/12",
    color: "pink/white",
    priceRub100: "29.0",
    priceEuro: "0.29",
    priceRub95: "27.6",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Supermodel",
    size: "12/+",
    color: "pink",
    priceRub100: "34.0",
    priceEuro: "0.34",
    priceRub95: "32.3",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Surrender",
    size: "12/+",
    color: "red",
    priceRub100: "31.0",
    priceEuro: "0.31",
    priceRub95: "29.5",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Surrender",
    size: "14/+",
    color: "red",
    priceRub100: "34.0",
    priceEuro: "0.34",
    priceRub95: "32.3",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Sweet Simone",
    size: "12/+",
    color: "pink",
    priceRub100: "35.1",
    priceEuro: "0.35",
    priceRub95: "33.3",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Swipe",
    size: "12/+",
    color: "pink",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Taiwan",
    size: "11/12",
    color: "pink",
    priceRub100: "32.8",
    priceEuro: "0.33",
    priceRub95: "31.2",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Taiwan",
    size: "12/+",
    color: "pink",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Tarzan",
    size: "12/+",
    color: "red/yellow",
    priceRub100: "36.0",
    priceEuro: "0.36",
    priceRub95: "34.2",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "The Edge",
    size: "12/+",
    color: "white",
    priceRub100: "38.5",
    priceEuro: "0.39",
    priceRub95: "36.6",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Thijs Boots ?®",
    size: "12/+",
    color: "salmon",
    priceRub100: "36.0",
    priceEuro: "0.36",
    priceRub95: "34.2",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Thunderball",
    size: "12/+",
    color: "red/yellow",
    priceRub100: "39.0",
    priceEuro: "0.39",
    priceRub95: "37.1",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Timeless",
    size: "12/+",
    color: "red/white",
    priceRub100: "32.0",
    priceEuro: "0.32",
    priceRub95: "30.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Tom Pouce",
    size: "12/+",
    color: "pink/yellow",
    priceRub100: "31.3",
    priceEuro: "0.31",
    priceRub95: "29.7",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Tresor",
    size: "12/+",
    color: "pink",
    priceRub100: "38.0",
    priceEuro: "0.38",
    priceRub95: "36.1",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Triple A",
    size: "12/+",
    color: "red/yellow",
    priceRub100: "26.0",
    priceEuro: "0.26",
    priceRub95: "24.7",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Triple A",
    size: "14/+",
    color: "red/yellow",
    priceRub100: "28.0",
    priceEuro: "0.28",
    priceRub95: "26.6",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Update",
    size: "12/+",
    color: "white",
    priceRub100: "38.3",
    priceEuro: "0.38",
    priceRub95: "36.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Upperbay",
    size: "12/+",
    color: "purple",
    priceRub100: "28.1",
    priceEuro: "0.28",
    priceRub95: "26.7",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Valdivia",
    size: "11/12",
    color: "orange",
    priceRub100: "31.1",
    priceEuro: "0.31",
    priceRub95: "29.6",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Valdivia",
    size: "12/+",
    color: "orange",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Valeska",
    size: "12/+",
    color: "pink/white",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Vanille Coupe",
    size: "12/+",
    color: "yellow",
    priceRub100: "32.0",
    priceEuro: "0.32",
    priceRub95: "30.4",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Vermont",
    size: "12/+",
    color: "pink/white",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Verona Love",
    size: "12/+",
    color: "pink",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Versaci",
    size: "12/+",
    color: "red",
    priceRub100: "28.1",
    priceEuro: "0.28",
    priceRub95: "26.7",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Vintage",
    size: "12/+",
    color: "pink",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Vuelta",
    size: "11/12",
    color: "red/yellow",
    priceRub100: "32.8",
    priceEuro: "0.33",
    priceRub95: "31.2",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "Vuelta",
    size: "12/+",
    color: "red/yellow",
    priceRub100: "36.3",
    priceEuro: "0.36",
    priceRub95: "34.5",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "White Dynasty",
    size: "12/+",
    color: "white",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "White Flag",
    size: "12/+",
    color: "white",
    priceRub100: "30.0",
    priceEuro: "0.30",
    priceRub95: "28.5",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "White Liberstar",
    size: "12/+",
    color: "white",
    priceRub100: "47.2",
    priceEuro: "0.47",
    priceRub95: "44.8",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "White Marvel",
    size: "12/+",
    color: "white",
    priceRub100: "33.0",
    priceEuro: "0.33",
    priceRub95: "31.4",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "White Master",
    size: "11/12",
    color: "white",
    priceRub100: "36.0",
    priceEuro: "0.36",
    priceRub95: "34.2",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "White Master",
    size: "12/+",
    color: "white",
    priceRub100: "45.0",
    priceEuro: "0.45",
    priceRub95: "42.8",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "White Mountain",
    size: "11/12",
    color: "white",
    priceRub100: "32.8",
    priceEuro: "0.33",
    priceRub95: "31.2",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "White Mountain",
    size: "12/+",
    color: "white",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "White Prince",
    size: "12/+",
    color: "white",
    priceRub100: "28.0",
    priceEuro: "0.28",
    priceRub95: "26.6",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "White River",
    size: "12/+",
    color: "white",
    priceRub100: "45.0",
    priceEuro: "0.45",
    priceRub95: "42.8",
  },
  {
    group: "Tulipa",
    sort: "db",
    name: "World Bowl",
    size: "12/+",
    color: "purple",
    priceRub100: "35.1",
    priceEuro: "0.35",
    priceRub95: "33.3",
  },
  {
    group: "Tulipa",
    sort: "dh",
    name: "Worlds Friend",
    size: "12/+",
    color: "red/yellow",
    priceRub100: "27.4",
    priceEuro: "0.27",
    priceRub95: "26.1",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Yellow Fabio",
    size: "12/+",
    color: "yellow",
    priceRub100: "30.0",
    priceEuro: "0.30",
    priceRub95: "28.5",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Yellow Master",
    size: "11/12",
    color: "yellow",
    priceRub100: "32.8",
    priceEuro: "0.33",
    priceRub95: "31.2",
  },
  {
    group: "Tulipa",
    sort: "tr",
    name: "Yellow Master",
    size: "12/+",
    color: "yellow",
    priceRub100: "36.8",
    priceEuro: "0.37",
    priceRub95: "34.9",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Yellow Valery",
    size: "12/+",
    color: "yellow",
    priceRub100: "33.3",
    priceEuro: "0.33",
    priceRub95: "31.7",
  },
  {
    group: "Tulipa",
    sort: "pa",
    name: "Zambesi",
    size: "12/+",
    color: "pink",
    priceRub100: "38.5",
    priceEuro: "0.39",
    priceRub95: "36.6",
  },
  {
    group: "Tulipa",
    sort: "fr",
    name: "Zanzibar",
    size: "12/+",
    color: "pink",
    priceRub100: "34.0",
    priceEuro: "0.34",
    priceRub95: "32.3",
  },
];

// Заполнение таблицы данными
const tableBody = document.querySelector("#price-table tbody");

priceData.forEach((item) => {
  const row = document.createElement("tr");
  row.innerHTML = `
                <td>${item.group}</td>
                <td>${item.name}</td>
                <td>${item.size}</td>
                <td>${item.color}</td>
                <td>${item.priceRub100}</td>
                <td>${item.priceEuro}</td>
                <td>${item.priceRub95}</td>
            `;
  tableBody.appendChild(row);
});

// Поиск по таблице
const searchInput = document.getElementById("search");
const noResults = document.getElementById("no-results");

searchInput.addEventListener("input", function () {
  const searchTerm = this.value.toLowerCase();
  const rows = tableBody.querySelectorAll("tr");
  let hasResults = false;

  rows.forEach((row) => {
    const cells = row.querySelectorAll("td");
    let rowMatches = false;

    cells.forEach((cell) => {
      if (cell.textContent.toLowerCase().includes(searchTerm)) {
        rowMatches = true;
      }
    });

    if (rowMatches) {
      row.style.display = "";
      hasResults = true;
    } else {
      row.style.display = "none";
    }
  });

  noResults.style.display = hasResults ? "none" : "block";
});

// Кнопка скачивания в Excel
document
  .getElementById("download-excel")
  .addEventListener("click", function (e) {
    e.preventDefault();

    // Создаем CSV содержимое
    let csvContent = "data:text/csv;charset=utf-8,";

    // Заголовки
    csvContent +=
      "Группа,Сорт,Размер,Цвет,Цена руб. (100р/евро),Цена евро,Цена руб. (95р/евро)\n";

    // Данные
    priceData.forEach((item) => {
      csvContent += `${item.group},${item.name},${item.size},${item.color},${item.priceRub100},${item.priceEuro},${item.priceRub95}\n`;
    });

    // Создаем ссылку для скачивания
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", "прайс-лист_луковиц_тюльпанов.csv");
    document.body.appendChild(link);

    // Запускаем скачивание
    link.click();

    // Удаляем ссылку
    document.body.removeChild(link);
  });
